PENDING_VERIFICATION_USER_KEY = "pending_verification_user_key"
PENDING_ENROLLMENT_USER_IDENTIFIER = "pending_enrollment_user_identifier"
VERIFICATION_METHOD_CODE = "next-verification_method_code"
VERIFIED_METHOD_CODES = "verified_method_codes"
USER_SELECT_HTML = "user_select.html"
FORM = "form"

DJANGO_AUTH_CHAIN = "django_auth_chain"
DJANGO_AUTH_CHAIN_USER_HOME = f"{DJANGO_AUTH_CHAIN}:user_home"
DJANGO_AUTH_CHAIN_USER_SELECT = f"{DJANGO_AUTH_CHAIN}:user_select"
DJANGO_AUTH_CHAIN_ENROLL = f"{DJANGO_AUTH_CHAIN}:enroll"
DJANGO_AUTH_CHAIN_VERIFY = f"{DJANGO_AUTH_CHAIN}:verify"
