PENDING_VERIFICATION_USER_KEY = "pending_verification_user_key"
PENDING_ENROLLMENT_USER_IDENTIFIER = "pending_enrollment_user_identifier"
VERIFIED_METHOD_CODES = "verified_method_codes"

DJANGO_AUTH_CHAIN = "django_auth_chain"
DJANGO_AUTH_CHAIN_USER_HOME = f"{DJANGO_AUTH_CHAIN}:user_home"
DJANGO_AUTH_CHAIN_USER_SELECT = f"{DJANGO_AUTH_CHAIN}:user_select"
DJANGO_AUTH_CHAIN_ENROLL = f"{DJANGO_AUTH_CHAIN}:enroll"
DJANGO_AUTH_CHAIN_VERIFY = f"{DJANGO_AUTH_CHAIN}:verify"
