# Generated by Django 6.1.1 on 2026-09-24 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDefaultAuthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_methods', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'order'), name='unique_group_step_order')],
            },
        ),
        migrations.CreateModel(
            name='UserAuthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throttle_failure_count', models.PositiveIntegerField(default=0)),
                ('throttle_failure_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('login_with_password', 'Can log in using a password')],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'order'), name='unique_user_step_order'), models.UniqueConstraint(fields=('user', 'code'), name='unique_user_method')],
            },
        ),
    ]
